package com.gruman.service.pixel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-10-13T13:33:06.317-04:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://www.grumman.com/service/Pixel/", name = "Pixel")
@XmlSeeAlso({com.grumman.schema.pixel.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Pixel {

    @WebMethod(operationName = "Pixel", action = "http://www.grumman.com/service/Pixel/Pixel")
    @WebResult(name = "pixelResponse", targetNamespace = "http://www.grumman.com/schema/Pixel", partName = "pixelResponse")
    public com.grumman.schema.pixel.PixelResponse pixel(
        @WebParam(partName = "pixelRequest", name = "pixelRequest", targetNamespace = "http://www.grumman.com/schema/Pixel")
        com.grumman.schema.pixel.PixelRequest pixelRequest
    );
}
