package com.grumman.service.pixel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-11-07T14:52:19.502-05:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://www.grumman.com/service/Pixel/", name = "Pixel")
@XmlSeeAlso({com.grumman.schema.pixelheader.ObjectFactory.class, com.grumman.schema.pixelattack.ObjectFactory.class, com.grumman.schema.pixelcharselect.ObjectFactory.class, com.grumman.schema.pixel.ObjectFactory.class, com.grumman.schema.pixelchar.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Pixel {

    @WebMethod(operationName = "PixelCharUpdate", action = "http://www.grumman.com/service/Pixel/Pixel")
    @WebResult(name = "pixelCharResponse", targetNamespace = "http://www.grumman.com/schema/PixelChar", partName = "pixelCharResponse")
    public com.grumman.schema.pixelchar.PixelCharResponse pixelCharUpdate(
        @WebParam(partName = "pixelCharRequest", name = "pixelCharRequest", targetNamespace = "http://www.grumman.com/schema/PixelChar")
        com.grumman.schema.pixelchar.PixelCharRequest pixelCharRequest,
        @WebParam(header = true, mode = Mode.IN, partName = "pixelHeader", name = "pixelHeader", targetNamespace = "http://www.grumman.com/schema/PixelHeader")
        Holder<com.grumman.schema.pixelheader.PixelHeader> pixelHeader
    );

    @WebMethod(operationName = "PixelCharSelect", action = "http://www.grumman.com/service/Pixel/Pixel")
    @WebResult(name = "pixelAbstractCharSelectResponse", targetNamespace = "http://www.grumman.com/schema/PixelCharSelect", partName = "pixelAbstractCharSelectResponse")
    public com.grumman.schema.pixelcharselect.PixelCharSelectResponse pixelCharSelect(
        @WebParam(partName = "pixelCharSelectRequest", name = "pixelCharSelectRequest", targetNamespace = "http://www.grumman.com/schema/PixelCharSelect")
        com.grumman.schema.pixelcharselect.PixelCharSelectRequest pixelCharSelectRequest,
        @WebParam(header = true, mode = Mode.IN, partName = "pixelHeader", name = "pixelHeader", targetNamespace = "http://www.grumman.com/schema/PixelHeader")
        Holder<com.grumman.schema.pixelheader.PixelHeader> pixelHeader
    );

    @WebMethod(operationName = "Pixel", action = "http://www.grumman.com/service/Pixel/Pixel")
    @WebResult(name = "pixelResponse", targetNamespace = "http://www.grumman.com/schema/Pixel", partName = "pixelResponse")
    public com.grumman.schema.pixel.PixelResponse pixel(
        @WebParam(partName = "pixelRequest", name = "pixelRequest", targetNamespace = "http://www.grumman.com/schema/Pixel")
        com.grumman.schema.pixel.PixelRequest pixelRequest,
        @WebParam(header = true, mode = Mode.IN, partName = "pixelHeader", name = "pixelHeader", targetNamespace = "http://www.grumman.com/schema/PixelHeader")
        Holder<com.grumman.schema.pixelheader.PixelHeader> pixelHeader
    );

    @WebMethod(operationName = "PixelAttack", action = "http://www.grumman.com/service/Pixel/Pixel")
    @WebResult(name = "pixelAttackResponse", targetNamespace = "http://www.grumman.com/schema/PixelAttack", partName = "pixelAttackResponse")
    public com.grumman.schema.pixelattack.PixelAttackResponse pixelAttack(
        @WebParam(partName = "pixelAttackRequest", name = "pixelAttackRequest", targetNamespace = "http://www.grumman.com/schema/PixelAttack")
        com.grumman.schema.pixelattack.PixelAttackRequest pixelAttackRequest,
        @WebParam(header = true, mode = Mode.IN, partName = "pixelHeader", name = "pixelHeader", targetNamespace = "http://www.grumman.com/schema/PixelHeader")
        Holder<com.grumman.schema.pixelheader.PixelHeader> pixelHeader
    );
}
